name: DEPLOY

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - "**"

jobs:
  validate-slc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::490752553772:role/github_oidc_role
          role-duration-seconds: 900
          aws-region: us-west-2

      - name: main test
        run: |
          instances=`aws ec2 describe-instances`;
          echo $instances


    
