name: DEPLOY

on:
  workflow_dispatch:
    inputs:
      projectname:
        required: true
        default: 'pse-forums'
        type: string

  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - "**"

jobs:
  validate-slc:
    runs-on: ubuntu-latest
    env: 
      PORJECT_NAME: ${{ github.event.inputs.projectname}}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::490752553772:role/github_oidc_role
          role-duration-seconds: 900
          aws-region: us-west-2

      - name: main test
        run: |
          echo ${{ env.PROJECT_NAME }}
          ./.github/scripts/get-instances.sh ${{ env.PROJECT_NAME }}


    
